import bcrypt from "bcryptjs";
import type { WizardState } from "@/types/wizard";
import type { ServiceRegistry, ServiceDefinition, WorkerDefinition } from "@/types/service-registry";
import { getAllEnabledServices, getInfraForServices } from "@/lib/compose-generator";
import { imageDigestFor } from "@/lib/image-digests";

interface AppKeyEntry {
  appId: string;
  rawKey: string;
  bcryptHash: string;
}

function generateAppKey(appId: string): AppKeyEntry {
  const bytes = new Uint8Array(48);
  crypto.getRandomValues(bytes);
  const rawKey = btoa(String.fromCharCode(...bytes))
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=/g, "");
  const bcryptHash = bcrypt.hashSync(rawKey, 12);
  return { appId, rawKey, bcryptHash };
}

/** A strong random secret (base64url, ~43 chars) — well above any length guard. */
function generateSecret(bytes = 32): string {
  const buf = new Uint8Array(bytes);
  crypto.getRandomValues(buf);
  return btoa(String.fromCharCode(...buf))
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=/g, "");
}

interface SecretsMap {
  pgPassword: string;
  redisPassword: string;
  authSecretKey: string;
  configAdminToken: string;
  authAdminToken: string;
  adminApiKey: string;
  grafanaPassword: string;
  modelServiceToken: string;
  mqttPassword: string;
  dbUser: string;
}

/**
 * Generates a fully self-contained docker-compose.yml with all values resolved inline.
 * No ${VAR} interpolation -- everything is baked in.
 */
export function generateComposeExport(
  state: WizardState,
  registry: ServiceRegistry,
  storagePath: string = "/var/lib/jarvis",
): string {
  const allEnabled = getAllEnabledServices(state, registry);
  const enabledIds = allEnabled.map((s) => s.id);
  const infra = getInfraForServices(enabledIds, registry);

  // Add mosquitto if available
  const mosquitto = registry.infrastructure.find((i) => i.id === "mosquitto");
  if (mosquitto && !infra.some((i) => i.id === "mosquitto")) {
    infra.push(mosquitto);
  }

  // Generate app keys for each service (except jarvis-admin)
  const appKeys = new Map<string, AppKeyEntry>();
  for (const svc of allEnabled) {
    if (svc.id === "jarvis-admin") continue;
    appKeys.set(svc.id, generateAppKey(svc.id));
  }

  // Resolve each secret to a strong value ONCE and reuse it everywhere. A wizard-
  // provided value wins; otherwise we generate a strong random secret (never a
  // "changeme" placeholder — which is both insecure and now rejected by services'
  // boot-time secret guard). Memoized by ref so the same secret is identical
  // across every service that references it (previously the SecretsMap fell back
  // to "changeme" while the generic env loop fell back to "" — a mismatch that
  // silently broke fleet-wide JWT validation on a partial-wizard export).
  const resolvedSecrets = new Map<string, string>();
  const resolveSecret = (ref: string): string => {
    const provided = state.secrets[ref];
    if (provided) return provided;
    let generated = resolvedSecrets.get(ref);
    if (!generated) {
      generated = generateSecret();
      resolvedSecrets.set(ref, generated);
    }
    return generated;
  };

  const secrets: SecretsMap = {
    pgPassword: resolveSecret("POSTGRES_PASSWORD"),
    redisPassword: resolveSecret("REDIS_PASSWORD"),
    authSecretKey: resolveSecret("AUTH_SECRET_KEY"),
    configAdminToken: resolveSecret("JARVIS_CONFIG_ADMIN_TOKEN"),
    authAdminToken: resolveSecret("JARVIS_AUTH_ADMIN_TOKEN"),
    adminApiKey: resolveSecret("ADMIN_API_KEY"),
    grafanaPassword: resolveSecret("GRAFANA_ADMIN_PASSWORD"),
    modelServiceToken: resolveSecret("MODEL_SERVICE_TOKEN"),
    mqttPassword: resolveSecret("MQTT_PASSWORD"),
    dbUser: state.dbUser || "jarvis",
  };

  // Collect databases from enabled services
  const databases = allEnabled
    .filter((s) => s.database)
    .map((s) => s.database!);
  const primaryDb = "jarvis_config";

  const lines: string[] = [];

  lines.push("# Jarvis Voice Assistant - Self-Contained Docker Compose");
  lines.push("# Generated by Jarvis Installer (compose-export mode)");
  lines.push("# All values are resolved inline - no .env file required");
  lines.push("");
  // Pin the Compose project name so it's identity-stable regardless of the
  // directory `docker compose` runs from. Without it, the fixed container_name:s
  // collide ("container name already in use") when the project is re-derived
  // from a different path (e.g. the admin container vs the host). 2026-06.
  lines.push("name: jarvis");
  lines.push("");
  lines.push("services:");

  // --- Infrastructure ---
  lines.push("");
  lines.push("  # ============================================================");
  lines.push("  # Infrastructure");
  lines.push("  # ============================================================");

  // PostgreSQL
  if (infra.some((i) => i.id === "postgres")) {
    const pgHostPort = state.infraPortOverrides["postgres"] ?? 5432;
    const additionalDbs = databases.filter((db) => db !== primaryDb);

    lines.push("");
    lines.push("  postgres:");
    lines.push("    image: pgvector/pgvector:pg16");
    lines.push("    container_name: jarvis-postgres");
    lines.push("    ports:");
    // Data-plane infra binds to loopback by default (override via JARVIS_INFRA_BIND_HOST)
    lines.push(`      - "\${JARVIS_INFRA_BIND_HOST:-127.0.0.1}:${pgHostPort}:5432"`);
    lines.push("    environment:");
    lines.push(`      POSTGRES_USER: "${secrets.dbUser}"`);
    lines.push(`      POSTGRES_PASSWORD: "${secrets.pgPassword}"`);
    lines.push(`      POSTGRES_DB: "${primaryDb}"`);
    // Create additional databases via init script + entrypoint override
    if (additionalDbs.length > 0) {
      lines.push("    entrypoint:");
      lines.push('      - sh');
      lines.push('      - -c');
      lines.push(`      - |`);
      lines.push(`        cat > /docker-entrypoint-initdb.d/create-dbs.sh << 'EOSH'`);
      lines.push(`        #!/bin/bash`);
      lines.push(`        set -e`);
      for (const db of additionalDbs) {
        lines.push(`        psql -v ON_ERROR_STOP=1 --username "$$POSTGRES_USER" --dbname "$$POSTGRES_DB" -tc "SELECT 1 FROM pg_database WHERE datname='${db}'" | grep -q 1 || psql -v ON_ERROR_STOP=1 --username "$$POSTGRES_USER" --dbname "$$POSTGRES_DB" -c "CREATE DATABASE ${db}"`);
      }
      lines.push(`        EOSH`);
      lines.push(`        chmod +x /docker-entrypoint-initdb.d/create-dbs.sh`);
      lines.push(`        exec docker-entrypoint.sh postgres`);
    }
    lines.push("    healthcheck:");
    lines.push(`      test: ["CMD-SHELL", "pg_isready -U ${secrets.dbUser}"]`);
    lines.push("      interval: 10s");
    lines.push("      timeout: 5s");
    lines.push("      retries: 5");
    lines.push("    volumes:");
    lines.push(`      - ${storagePath}/postgres:/var/lib/postgresql/data`);
    lines.push("    networks:");
    lines.push("      - jarvis");
    lines.push("    restart: unless-stopped");
  }

  // Redis
  if (infra.some((i) => i.id === "redis")) {
    const redisHostPort = state.infraPortOverrides["redis"] ?? 6379;
    lines.push("");
    lines.push("  redis:");
    lines.push("    image: redis:7-alpine");
    lines.push("    container_name: jarvis-redis");
    lines.push("    ports:");
    // Data-plane infra binds to loopback by default (override via JARVIS_INFRA_BIND_HOST)
    lines.push(`      - "\${JARVIS_INFRA_BIND_HOST:-127.0.0.1}:${redisHostPort}:6379"`);
    lines.push(`    command: redis-server --requirepass "${secrets.redisPassword}"`);
    lines.push("    volumes:");
    lines.push(`      - ${storagePath}/redis:/data`);
    lines.push("    networks:");
    lines.push("      - jarvis");
    lines.push("    restart: unless-stopped");
  }

  // Loki
  if (infra.some((i) => i.id === "loki")) {
    const lokiHostPort = state.infraPortOverrides["loki"] ?? 3100;
    lines.push("");
    lines.push("  loki:");
    lines.push("    image: grafana/loki:2.9.0");
    lines.push("    container_name: jarvis-loki");
    lines.push("    user: \"0\"");
    lines.push("    ports:");
    lines.push(`      - "${lokiHostPort}:3100"`);
    lines.push("    volumes:");
    lines.push(`      - ${storagePath}/loki:/loki`);
    lines.push("    networks:");
    lines.push("      - jarvis");
    lines.push("    restart: unless-stopped");
  }

  // Grafana
  if (infra.some((i) => i.id === "grafana")) {
    const grafanaHostPort = state.infraPortOverrides["grafana"] ?? 3000;
    lines.push("");
    lines.push("  grafana:");
    lines.push("    image: grafana/grafana:latest");
    lines.push("    container_name: jarvis-grafana");
    lines.push("    user: \"0\"");
    lines.push("    ports:");
    lines.push(`      - "${grafanaHostPort}:3000"`);
    lines.push("    environment:");
    lines.push(`      GF_SECURITY_ADMIN_PASSWORD: "${secrets.grafanaPassword}"`);
    lines.push("    volumes:");
    lines.push(`      - ${storagePath}/grafana:/var/lib/grafana`);
    lines.push("    networks:");
    lines.push("      - jarvis");
    lines.push("    restart: unless-stopped");
  }

  // Mosquitto — raw MQTT (LAN) + WebSockets (external nodes via Cloudflare Tunnel).
  // Auth: hash the shared MQTT credential into a password_file at startup (the
  // generator can't produce mosquitto's $7$ PBKDF2 hash), then serve an env-driven
  // allow_anonymous. This is a FRESH install: the command-center reads
  // MQTT_PASSWORD from its env and every node fetches broker creds over
  // authenticated HTTP before it opens an MQTT connection, so there is no
  // anonymous client to strand — it defaults FALSE (locked) to close the
  // anonymous-broker RCE window from the first boot. Set MQTT_ALLOW_ANON=true
  // only if adopting an old fleet whose nodes predate credential auto-fetch. The
  // password is inlined into the env (self-contained export); `$$` escapes
  // Compose interpolation so the container shell expands the vars.
  if (infra.some((i) => i.id === "mosquitto")) {
    const mqttHostPort = state.infraPortOverrides["mosquitto"] ?? 1884;
    const mqttWsHostPort = state.infraPortOverrides["mosquitto-ws"] ?? 9883;
    lines.push("");
    lines.push("  mosquitto:");
    lines.push("    image: eclipse-mosquitto:2.0");
    lines.push("    container_name: jarvis-mosquitto");
    lines.push("    ports:");
    lines.push(`      - "${mqttHostPort}:1883"`);
    lines.push(`      - "${mqttWsHostPort}:9001"`);
    lines.push("    environment:");
    lines.push('      MQTT_USERNAME: "jarvis"');
    lines.push(`      MQTT_PASSWORD: "${secrets.mqttPassword}"`);
    lines.push('      MQTT_ALLOW_ANON: "${MQTT_ALLOW_ANON:-false}"');
    lines.push("    command:");
    lines.push("      - sh");
    lines.push("      - -c");
    lines.push("      - |");
    // rm -f: mosquitto_passwd -c refuses an existing file on restart (2.1+).
    // chown: mosquitto drops privileges to the mosquitto user BEFORE reading
    // the password file (2.0.22+/2.1 image rebuilds), so a root-owned 0600
    // pwfile crash-loops the broker on every fresh install.
    lines.push("        rm -f /tmp/pwfile");
    lines.push('        mosquitto_passwd -b -c /tmp/pwfile "$$MQTT_USERNAME" "$$MQTT_PASSWORD"');
    lines.push("        chown mosquitto:mosquitto /tmp/pwfile");
    lines.push("        echo 'listener 1883' > /tmp/mosquitto.conf");
    lines.push("        echo 'protocol mqtt' >> /tmp/mosquitto.conf");
    lines.push("        echo 'listener 9001' >> /tmp/mosquitto.conf");
    lines.push("        echo 'protocol websockets' >> /tmp/mosquitto.conf");
    lines.push('        echo "allow_anonymous $$MQTT_ALLOW_ANON" >> /tmp/mosquitto.conf');
    lines.push("        echo 'password_file /tmp/pwfile' >> /tmp/mosquitto.conf");
    lines.push("        exec mosquitto -c /tmp/mosquitto.conf -v");
    lines.push("    volumes:");
    lines.push(`      - ${storagePath}/mosquitto:/mosquitto/data`);
    lines.push("    networks:");
    lines.push("      - jarvis");
    lines.push("    restart: unless-stopped");
  }

  // --- Services ---
  lines.push("");
  lines.push("  # ============================================================");
  lines.push("  # Jarvis Services");
  lines.push("  # ============================================================");

  for (const service of allEnabled) {
    lines.push("");
    lines.push(
      ...generateExportServiceBlock(
        service,
        state,
        registry,
        appKeys,
        secrets,
        allEnabled,
        storagePath,
        resolveSecret,
      ),
    );
    if (service.workers) {
      for (const worker of service.workers) {
        lines.push("");
        lines.push(
          ...generateExportWorkerBlock(
            worker,
            service,
            state,
            registry,
            appKeys,
            secrets,
            allEnabled,
            storagePath,
            resolveSecret,
          ),
        );
      }
    }
  }

  // Networks
  lines.push("");
  lines.push("networks:");
  lines.push("  jarvis:");
  lines.push("    driver: bridge");

  // Named volumes. Infra uses bind mounts (${storagePath}/...), so only the
  // app-level named volumes referenced in service blocks need declaring here —
  // an undeclared named volume makes the whole compose project invalid.
  const namedVolumes = new Set<string>();
  if (allEnabled.some((s) => s.id === "jarvis-whisper-api")) {
    namedVolumes.add("whisper-voice-profiles");
  }
  if (allEnabled.some((s) => s.id === "jarvis-command-center")) {
    namedVolumes.add("command-center-prompt-providers");
  }
  if (namedVolumes.size > 0) {
    lines.push("");
    lines.push("volumes:");
    for (const vol of namedVolumes) {
      lines.push(`  ${vol}:`);
    }
  }

  lines.push("");
  return lines.join("\n");
}

function getContainerPort(service: ServiceDefinition): number {
  return service.containerPort ?? service.port;
}

/**
 * GPU types we publish image variants for on `cpuFallback` services.
 * Other GPU types (amd Vulkan, none) fall back to the plain CPU image.
 */
const CPU_FALLBACK_GPU_VARIANTS = new Set<string>(["nvidia", "amd-rocm"]);

// Whisper's variant is chosen EXPLICITLY via state.whisperBackend (default "cpu"),
// independent of the auto-detected LLM gpuType. cpu -> plain image; cuda/vulkan/
// rocm -> the matching published suffix. WHISPER_BACKEND_GPU maps the selection to
// the gpuType the device emitter understands.
const WHISPER_BACKEND_SUFFIX: Record<string, string> = {
  cpu: "",
  cuda: "-cuda",
  vulkan: "-vulkan",
  rocm: "-rocm",
};
const WHISPER_BACKEND_GPU: Record<string, string> = {
  cpu: "none",
  cuda: "nvidia",
  vulkan: "amd",
  rocm: "amd-rocm",
};

function shouldUseGpuVariant(service: ServiceDefinition, gpuType: string): boolean {
  if (!service.gpu) return false;
  if (service.cpuFallback && !CPU_FALLBACK_GPU_VARIANTS.has(gpuType)) return false;
  return true;
}

function getExportImage(service: ServiceDefinition, state: WizardState): string {
  const image = service.image;
  if (!image.startsWith("ghcr.io/alexberardi/")) return image;
  const baseImage = image.includes(":") ? image.slice(0, image.lastIndexOf(":")) : image;

  // Variant suffix: whisper's explicit backend (cpu default), else the LLM gpu variant.
  let suffix = "";
  if (service.id === "jarvis-whisper-api") {
    suffix = WHISPER_BACKEND_SUFFIX[state.whisperBackend] ?? "";
  } else if (shouldUseGpuVariant(service, state.gpuType)) {
    const variantSuffix: Record<string, string> = {
      nvidia: "-cuda",
      amd: "-vulkan",
      "amd-rocm": "-rocm",
      none: "-cpu",
    };
    suffix = variantSuffix[state.gpuType] ?? "-cpu";
  }

  // Export bakes values inline (no ${VAR}). Pin by digest when recorded, else the
  // literal track tag.
  const track = state.releaseTrack === "dev" ? "dev" : "latest";
  const digest = imageDigestFor(baseImage, track, suffix);
  if (digest) return `${baseImage}@${digest}`;
  return `${baseImage}:${track}${suffix}`;
}

function pushGpuDevices(lines: string[], gpuType: string): void {
  if (gpuType === "nvidia") {
    lines.push("    ipc: host");
    lines.push('    shm_size: "8gb"');
    lines.push("    deploy:");
    lines.push("      resources:");
    lines.push("        reservations:");
    lines.push("          devices:");
    lines.push("            - driver: nvidia");
    lines.push("              count: all");
    lines.push("              capabilities: [gpu]");
  } else if (gpuType === "amd" || gpuType === "amd-rocm") {
    lines.push("    devices:");
    lines.push("      - /dev/dri:/dev/dri");
    lines.push("      - /dev/kfd:/dev/kfd");
    lines.push("    ipc: host");
    lines.push('    shm_size: "8gb"');
    lines.push("    group_add:");
    lines.push("      - video");
    lines.push("      - render");
  }
}

function pushExportGpuConfig(
  lines: string[],
  service: ServiceDefinition,
  state: WizardState,
): void {
  // Whisper: device passthrough follows the explicit whisperBackend selection,
  // not the auto-detected LLM gpuType. cpu -> nothing.
  if (service.id === "jarvis-whisper-api") {
    pushGpuDevices(lines, WHISPER_BACKEND_GPU[state.whisperBackend] ?? "none");
    return;
  }
  if (!shouldUseGpuVariant(service, state.gpuType) || !state.gpuEnabled) return;
  pushGpuDevices(lines, state.gpuType);
}

/**
 * Env shared by the llm-proxy API container and its queue worker. Both MUST
 * carry the SAME MODEL_SERVICE_TOKEN: the worker authenticates its calls to
 * the model service (port 7705) with it, and the model service fails closed —
 * every inference call 503s (with /health still green) when the token is unset.
 */
function pushLlmProxySharedEnv(
  lines: string[],
  state: WizardState,
  secrets: SecretsMap,
): void {
  lines.push("      # Model service (7705) internal auth — it rejects all inference calls with 503 when unset");
  lines.push(`      MODEL_SERVICE_TOKEN: "${secrets.modelServiceToken}"`);
  if (state.gpuType === "amd" || state.gpuType === "amd-rocm") {
    lines.push("      # Flash attention's HIP kernel faults natively on RDNA4 (gfx1201); false is also faster there");
    lines.push('      JARVIS_FLASH_ATTN: "false"');
  }
}

function generateExportServiceBlock(
  service: ServiceDefinition,
  state: WizardState,
  registry: ServiceRegistry,
  appKeys: Map<string, AppKeyEntry>,
  secrets: SecretsMap,
  allEnabled: ServiceDefinition[],
  storagePath: string,
  resolveSecret: (ref: string) => string,
): string[] {
  const lines: string[] = [];
  const hostPort = state.portOverrides[service.id] ?? service.port;
  const containerPort = getContainerPort(service);

  const image = getExportImage(service, state);

  lines.push(`  ${service.id}:`);
  lines.push(`    image: ${image}`);
  lines.push(`    container_name: ${service.id}`);

  // Ports
  lines.push("    ports:");
  lines.push(`      - "${hostPort}:${containerPort}"`);

  // Environment
  lines.push("    environment:");
  // Prod deployment: opt every service into strict boot-time secret enforcement.
  // Safe here because the export bakes strong generated secrets (above), so the
  // guard has nothing to trip on; it protects against a later manual weakening.
  lines.push('      JARVIS_ENV: "production"');

  // Discovery URL style. In a compose deployment, in-container services reach
  // shared infra registered as `localhost` (e.g. the MQTT broker) via the host —
  // `dockerized` makes config-service rewrite localhost → host.docker.internal
  // (reachable through the extra_hosts host-gateway + the published port). It only
  // rewrites localhost entries; container-name entries stay on the bridge. This is
  // what lets ONE broker registry entry (localhost) resolve for both in-Docker
  // services (→ host.docker.internal) and remote Pi nodes (→ server IP via remote
  // style). Without it, a localhost broker entry would point a container at itself.
  lines.push('      JARVIS_CONFIG_URL_STYLE: "dockerized"');

  // DATABASE_URL
  if (service.database) {
    const driver = service.dbDriverPrefix ?? "postgresql://";
    const dbUrl = `${driver}${secrets.dbUser}:${secrets.pgPassword}@postgres:5432/${service.database}`;
    lines.push(`      DATABASE_URL: "${dbUrl}"`);
    lines.push(`      MIGRATIONS_DATABASE_URL: "${dbUrl}"`);
  }

  // App-to-app credentials
  const appKey = appKeys.get(service.id);
  if (appKey) {
    lines.push(`      JARVIS_APP_ID: "${service.id}"`);
    lines.push(`      JARVIS_APP_KEY: "${appKey.rawKey}"`);
  }

  // Service-specific env vars (skip DATABASE_URL and MIGRATIONS_DATABASE_URL, already handled)
  for (const env of service.envVars) {
    if (env.name === "DATABASE_URL" || env.name === "MIGRATIONS_DATABASE_URL") continue;

    if (env.secretRef) {
      const value = resolveSecret(env.secretRef);
      lines.push(`      ${env.name}: "${value}"`);
    } else if (env.default) {
      lines.push(`      ${env.name}: "${env.default}"`);
    }
  }

  // JARVIS_AUTH_BASE_URL for services that depend on auth (not auth itself)
  const authService = allEnabled.find((s) => s.id === "jarvis-auth");
  if (service.id !== "jarvis-auth" && service.dependsOn.includes("jarvis-auth") && authService) {
    const authContainerPort = getContainerPort(authService);
    lines.push(`      JARVIS_AUTH_BASE_URL: "http://jarvis-auth:${authContainerPort}"`);
  }

  // Service-specific extra env vars
  if (service.id === "jarvis-command-center") {
    // CC validates user JWTs locally (verify_user_jwt) with the shared secret.
    // Without it, every user-authenticated CC endpoint (e.g. node K2 provision,
    // settings writes) 500s with "JARVIS_AUTH_SECRET_KEY not configured".
    lines.push(`      JARVIS_AUTH_SECRET_KEY: "${secrets.authSecretKey}"`);
    lines.push('      JARVIS_AUTH_ALGORITHM: "HS256"');
    // CC publishes to nodes over MQTT (K2 provision, settings push, tool
    // dispatch, package install). Without the broker URL it defaults to
    // localhost:1883 inside its own container and every publish 503s
    // ("MQTT not available"). Point it at the mosquitto container.
    lines.push('      JARVIS_MQTT_BROKER_URL: "mqtt://jarvis-mosquitto:1883"');
    // Shared broker credential — the same secret the mosquitto password_file is
    // built from. CC's get_mqtt_credentials() reads these to authenticate; it
    // also hands them to nodes over authenticated HTTP (/mqtt-credentials).
    lines.push('      MQTT_USERNAME: "jarvis"');
    lines.push(`      MQTT_PASSWORD: "${secrets.mqttPassword}"`);
  }

  if (service.id === "jarvis-command-center" && state.llmInterface) {
    lines.push(`      LLM_INTERFACE_SEED: "${state.llmInterface}"`);
  }

  if (service.id === "jarvis-command-center" && state.relayEnabled) {
    lines.push(`      JARVIS_RELAY_URL: "${state.relayUrl || 'https://relay.jarvisautomation.io'}"`);
  }

  // Notifications → relay: inject URL + household JWT when relay is enabled.
  // The notifications Python code reads RELAY_URL / RELAY_HOUSEHOLD_JWT.
  // Without both, _deliver_via_relay short-circuits and push silently no-ops.
  if (service.id === "jarvis-notifications" && state.relayEnabled) {
    lines.push(`      RELAY_URL: "${state.relayUrl || 'https://relay.jarvisautomation.io'}"`);
    lines.push(`      RELAY_HOUSEHOLD_JWT: "${state.relayHouseholdJwt ?? ''}"`);
  }

  if (
    service.id === "jarvis-command-center" &&
    state.enabledModules.includes("go2rtc")
  ) {
    const go2rtcPort = state.portOverrides["go2rtc"] ?? 1984;
    lines.push(`      GO2RTC_URL: "http://go2rtc:${go2rtcPort}"`);
  }

  if (service.id === "jarvis-llm-proxy-api") {
    lines.push('      MODEL_SERVICE_URL: "http://localhost:7705"');
    lines.push('      MODEL_SERVICE_PORT: "7705"');
    lines.push('      VLLM_WORKER_MULTIPROC_METHOD: "spawn"');
    lines.push('      JARVIS_MODEL_BACKEND: "GGUF"');
    lines.push('      JARVIS_MODEL_CHAT_FORMAT: "chatml"');
    lines.push('      JARVIS_MODEL_CONTEXT_WINDOW: "32768"');
    lines.push(`      REDIS_URL: "redis://:${secrets.redisPassword}@redis:6379/0"`);
    pushLlmProxySharedEnv(lines, state, secrets);
  }

  if (service.id === "jarvis-settings-server") {
    lines.push(`      JARVIS_AUTH_SECRET_KEY: "${secrets.authSecretKey}"`);
    lines.push('      JARVIS_AUTH_ALGORITHM: "HS256"');
  }

  if (service.id === "jarvis-admin") {
    lines.push('      JARVIS_DEPLOY_MODE: "compose-export"');
  }

  // Whisper model override
  const isWhisper = service.id === "jarvis-whisper-api";
  const nonDefaultWhisper = isWhisper && state.whisperModel !== "base.en";
  if (nonDefaultWhisper) {
    lines.push(`      WHISPER_MODEL: "/whisper-models/ggml-${state.whisperModel}.bin"`);
  }

  // Migration entrypoint wrapper. Services flagged `migrate: true` in the
  // registry run `alembic upgrade head` before their normal CMD/command. We
  // override the entrypoint (none of these images set ENTRYPOINT; all use CMD)
  // with a wrapper that migrates, then `exec "$@"` runs whatever args land —
  // either the image's own CMD or the explicit `command:` block below. The
  // "jarvis-migrate" token is the $0 placeholder so the real args go to "$@".
  if (service.migrate) {
    lines.push("    entrypoint:");
    lines.push("      - /bin/sh");
    lines.push("      - -c");
    lines.push('      - python -m alembic upgrade head && exec "$@"');
    lines.push("      - jarvis-migrate");
  }

  // Command with seed scripts. These become the args the migrate entrypoint
  // execs AFTER migration, so seeding runs against an up-to-date schema. The
  // leading `alembic upgrade head` is no longer emitted here — the entrypoint
  // owns migration now.
  if (service.id === "jarvis-auth") {
    lines.push("    command:");
    lines.push("      - sh");
    lines.push("      - -c");
    lines.push("      - |");
    for (const line of generateAuthSeedScript(appKeys, containerPort).split("\n")) {
      lines.push(`        ${line}`);
    }
  } else if (service.id === "jarvis-config-service") {
    lines.push("    command:");
    lines.push("      - sh");
    lines.push("      - -c");
    lines.push("      - |");
    for (const line of generateConfigSeedScript(allEnabled, containerPort, state).split("\n")) {
      lines.push(`        ${line}`);
    }
  } else if (service.id === "jarvis-llm-proxy-api") {
    // The migrate entrypoint above clears the image CMD, so llm-proxy MUST keep
    // an explicit command — and it MUST be the image's supervised launcher
    // scripts/serve.sh (API in the foreground + model service respawned with
    // backoff), NOT the old unsupervised `uvicorn model_service & exec uvicorn
    // main` pattern: when the model service crashed natively, nothing respawned
    // it and the API 503'd forever (2026-07-02 outage). serve.sh defaults
    // SERVER_PORT=7704 / MODEL_SERVICE_PORT=7705, matching what we publish.
    lines.push('    command: ["bash", "scripts/serve.sh"]');
  } else if (service.migrate) {
    // Overriding `entrypoint` CLEARS the image's CMD, so a migrate service with
    // no explicit command would `exec ""` (empty $@) and exit right after
    // migrating — the container restart-loops with no server. Re-emit the
    // image's serve command so the migrate entrypoint execs it. These services
    // (command-center, whisper, notifications) all serve `app.main:app`.
    lines.push(
      `    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "${containerPort}"]`,
    );
  }

  // Dependencies
  if (service.dependsOn.length > 0) {
    lines.push("    depends_on:");
    for (const dep of service.dependsOn) {
      const isInfra = registry.infrastructure.some((i) => i.id === dep);
      if (isInfra && dep === "postgres") {
        lines.push(`      ${dep}:`);
        lines.push("        condition: service_healthy");
      } else if (isInfra) {
        lines.push(`      ${dep}:`);
        lines.push("        condition: service_started");
      } else {
        const depEnabled = allEnabled.some((s) => s.id === dep);
        if (depEnabled) {
          lines.push(`      ${dep}:`);
          lines.push("        condition: service_started");
        }
      }
    }
  }

  // Volumes
  const vols: string[] = [];
  if (isWhisper) {
    vols.push(`      - ${storagePath}/whisper-models:/whisper-models:ro`);
    vols.push("      - whisper-voice-profiles:/app/voice_profiles");
  }
  // modelVolume: only LLM-style services that load weights from disk need this
  // bind. Whisper bakes its model into the image and shouldn't get a stray mount.
  if (service.modelVolume) {
    vols.push(`      - ${storagePath}/models:/app/.models`);
  }
  // Service-declared mounts from the registry (e.g. /var/run/docker.sock,
  // ${HOME}/.jarvis/compose:/host/compose for jarvis-admin).
  if (service.volumes) {
    for (const vol of service.volumes) {
      vols.push(`      - ${vol}`);
    }
  }
  if (vols.length > 0) {
    lines.push("    volumes:");
    lines.push(...vols);
  }

  // extra_hosts for reaching host services
  lines.push("    extra_hosts:");
  lines.push('      - "host.docker.internal:host-gateway"');

  pushExportGpuConfig(lines, service, state);

  // Healthcheck. Pick a probe that's guaranteed to exist in the service's own
  // image — curl is NOT installed in several service images (config/auth/logs/
  // tts/notifications), so a curl probe marks them "unhealthy" forever even
  // while they serve fine.
  //  - admin / web: Node images → node http.get
  //  - everything else: Python/uvicorn images → python + urllib (always present,
  //    since these services boot via python/uvicorn)
  lines.push("    healthcheck:");
  const healthUrl = `http://localhost:${containerPort}${service.healthCheck}`;
  if (service.id === "jarvis-admin" || service.id === "jarvis-web") {
    lines.push(
      `      test: ["CMD", "node", "-e", "require('http').get('${healthUrl}', r => process.exit(r.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))"]`,
    );
  } else {
    lines.push(
      `      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('${healthUrl}')"]`,
    );
  }
  lines.push("      interval: 30s");
  lines.push("      timeout: 10s");
  lines.push("      retries: 3");
  if (service.id === "jarvis-llm-proxy-api") {
    lines.push("      start_period: 120s");
  } else if (service.database) {
    lines.push("      start_period: 30s");
  }

  lines.push("    networks:");
  lines.push("      - jarvis");
  lines.push("    restart: unless-stopped");

  return lines;
}

function generateAuthSeedScript(
  appKeys: Map<string, AppKeyEntry>,
  authContainerPort: number,
): string {
  // Escape $ as $$ for Docker Compose (it interpolates $ in ALL string values
  // including block scalars). Then single quotes around python -c prevent shell
  // from expanding what's left.
  const clientLines: string[] = [];
  for (const [, entry] of appKeys) {
    // Double every $ so Docker Compose passes them through literally
    const escapedHash = entry.bcryptHash.replace(/\$/g, "$$$$");
    clientLines.push(
      `    ("${entry.appId}", "${escapedHash}"),`,
    );
  }

  // Migration is handled by the service's migrate entrypoint (registry
  // `migrate: true`); this seed script runs AFTER it, so the schema exists.
  return `python -c '
from jarvis_auth.app.db.session import SessionLocal
from jarvis_auth.app.db import models
from datetime import datetime, timezone
db = SessionLocal()
clients = [
${clientLines.join("\n")}
]
for app_id, key_hash in clients:
    if not db.query(models.AppClient).filter(models.AppClient.app_id == app_id).first():
        db.add(models.AppClient(app_id=app_id, name=app_id, key_hash=key_hash, is_active=True, created_at=datetime.now(timezone.utc)))
        print(f"Seeded app client: {app_id}")
db.commit()
db.close()
print("Auth seed complete")
'
exec uvicorn jarvis_auth.app.main:app --host 0.0.0.0 --port ${authContainerPort}`;
}

function generateConfigSeedScript(
  allEnabled: ServiceDefinition[],
  configContainerPort: number,
  state: WizardState,
): string {
  // Each row carries BOTH the internal container coords (host=container name,
  // port=container port) for direct container-to-container discovery AND the
  // externally-reachable published coords (external_host=localhost, the
  // published host port) so an off-docker client (mobile, via ?style=external)
  // gets a reachable URL. external_host="localhost" is the sentinel the client
  // rewrites to the host it reached config-service on.
  // Use double quotes for Python strings since outer python -c uses single quotes
  const serviceLines: string[] = [];
  for (const svc of allEnabled) {
    const cPort = getContainerPort(svc);
    const publishedPort = state.portOverrides[svc.id] ?? svc.port;
    const desc = svc.description.replace(/"/g, '\\"');
    serviceLines.push(
      `    ("${svc.id}", "${svc.id}", ${cPort}, "http", "${svc.healthCheck}", "${desc}", "localhost", ${publishedPort}),`,
    );
  }

  // MQTT broker — registered as the neutral `localhost` (NOT host.docker.internal,
  // which a remote Pi node cannot resolve). With this, the single entry resolves
  // per-consumer: in-Docker services (dockerized style) → host.docker.internal,
  // remote nodes (remote style) → the server IP. Both land on the published port.
  const mqttPublishedPort = state.infraPortOverrides["mosquitto"] ?? 1884;
  serviceLines.push(
    `    ("jarvis-mqtt-broker", "localhost", ${mqttPublishedPort}, "mqtt", "", "MQTT message broker (Mosquitto)", "localhost", ${mqttPublishedPort}),`,
  );

  // Migration is handled by the service's migrate entrypoint (registry
  // `migrate: true`); this seed script runs AFTER it, so the schema (including
  // the external_host/external_port columns) exists before we INSERT.
  return `python -c '
from app.database import SessionLocal
from app.models import Service
db = SessionLocal()
services = [
${serviceLines.join("\n")}
]
for name, host, port, scheme, health, desc, ext_host, ext_port in services:
    if not db.query(Service).filter(Service.name == name).first():
        db.add(Service(name=name, host=host, port=port, scheme=scheme, health_path=health, description=desc, external_host=ext_host, external_port=ext_port))
        print(f"Registered service: {name}")
db.commit()
db.close()
print("Config seed complete")
'
exec uvicorn app.main:app --host 0.0.0.0 --port ${configContainerPort}`;
}

function generateExportWorkerBlock(
  worker: WorkerDefinition,
  parent: ServiceDefinition,
  state: WizardState,
  registry: ServiceRegistry,
  appKeys: Map<string, AppKeyEntry>,
  secrets: SecretsMap,
  allEnabled: ServiceDefinition[],
  storagePath: string,
  resolveSecret: (ref: string) => string,
): string[] {
  const lines: string[] = [];
  const image = getExportImage(parent, state);
  const overrides = worker.envOverrides ?? {};
  const overrideKeys = new Set(Object.keys(overrides));

  lines.push(`  ${worker.id}:`);
  lines.push(`    image: ${image}`);
  lines.push(`    container_name: ${worker.id}`);

  lines.push("    environment:");

  if (parent.database) {
    const driver = parent.dbDriverPrefix ?? "postgresql://";
    const dbUrl = `${driver}${secrets.dbUser}:${secrets.pgPassword}@postgres:5432/${parent.database}`;
    if (!overrideKeys.has("DATABASE_URL")) lines.push(`      DATABASE_URL: "${dbUrl}"`);
    if (!overrideKeys.has("MIGRATIONS_DATABASE_URL")) {
      lines.push(`      MIGRATIONS_DATABASE_URL: "${dbUrl}"`);
    }
  }

  // Worker shares the parent's app credentials (same app id).
  const appKey = appKeys.get(parent.id);
  if (appKey) {
    if (!overrideKeys.has("JARVIS_APP_ID")) {
      lines.push(`      JARVIS_APP_ID: "${parent.id}"`);
    }
    if (!overrideKeys.has("JARVIS_APP_KEY")) {
      lines.push(`      JARVIS_APP_KEY: "${appKey.rawKey}"`);
    }
  }

  for (const env of parent.envVars) {
    if (env.name === "DATABASE_URL" || env.name === "MIGRATIONS_DATABASE_URL") continue;
    if (overrideKeys.has(env.name)) continue;
    if (env.secretRef) {
      const value = resolveSecret(env.secretRef);
      lines.push(`      ${env.name}: "${value}"`);
    } else if (env.default) {
      lines.push(`      ${env.name}: "${env.default}"`);
    }
  }

  const authService = allEnabled.find((s) => s.id === "jarvis-auth");
  if (
    parent.id !== "jarvis-auth" &&
    parent.dependsOn.includes("jarvis-auth") &&
    authService &&
    !overrideKeys.has("JARVIS_AUTH_BASE_URL")
  ) {
    const authContainerPort = getContainerPort(authService);
    lines.push(`      JARVIS_AUTH_BASE_URL: "http://jarvis-auth:${authContainerPort}"`);
  }

  if (parent.id === "jarvis-llm-proxy-api") {
    const llmProxyEnv: Array<[string, string]> = [
      ["MODEL_SERVICE_URL", '"http://localhost:7705"'],
      ["MODEL_SERVICE_PORT", '"7705"'],
      ["VLLM_WORKER_MULTIPROC_METHOD", '"spawn"'],
      ["JARVIS_MODEL_BACKEND", '"GGUF"'],
      ["JARVIS_MODEL_CHAT_FORMAT", '"chatml"'],
      ["JARVIS_MODEL_CONTEXT_WINDOW", '"32768"'],
      ["REDIS_URL", `"redis://:${secrets.redisPassword}@redis:6379/0"`],
    ];
    for (const [key, val] of llmProxyEnv) {
      if (!overrideKeys.has(key)) lines.push(`      ${key}: ${val}`);
    }
    pushLlmProxySharedEnv(lines, state, secrets);
  }

  for (const [key, val] of Object.entries(overrides)) {
    lines.push(`      ${key}: "${val}"`);
  }

  lines.push(`    command: ${worker.command}`);

  lines.push("    depends_on:");
  lines.push(`      ${parent.id}:`);
  lines.push("        condition: service_healthy");
  for (const dep of parent.dependsOn) {
    const isInfra = registry.infrastructure.some((i) => i.id === dep);
    if (!isInfra) continue;
    lines.push(`      ${dep}:`);
    lines.push(`        condition: ${dep === "postgres" ? "service_healthy" : "service_started"}`);
  }

  pushExportGpuConfig(lines, parent, state);

  const vols: string[] = [];
  if (parent.modelVolume) {
    vols.push(`      - ${storagePath}/models:/app/.models`);
  }
  if (vols.length > 0) {
    lines.push("    volumes:");
    lines.push(...vols);
  }

  lines.push("    extra_hosts:");
  lines.push('      - "host.docker.internal:host-gateway"');

  lines.push("    networks:");
  lines.push("      - jarvis");
  lines.push("    restart: unless-stopped");

  return lines;
}
