import bcrypt from "bcryptjs";
import type { WizardState } from "@/types/wizard";
import type { ServiceRegistry, ServiceDefinition } from "@/types/service-registry";
import { getAllEnabledServices, getInfraForServices } from "@/lib/compose-generator";

interface AppKeyEntry {
  appId: string;
  rawKey: string;
  bcryptHash: string;
}

function generateAppKey(appId: string): AppKeyEntry {
  const bytes = new Uint8Array(48);
  crypto.getRandomValues(bytes);
  const rawKey = btoa(String.fromCharCode(...bytes))
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=/g, "");
  const bcryptHash = bcrypt.hashSync(rawKey, 12);
  return { appId, rawKey, bcryptHash };
}

interface SecretsMap {
  pgPassword: string;
  redisPassword: string;
  authSecretKey: string;
  configAdminToken: string;
  authAdminToken: string;
  adminApiKey: string;
  dbUser: string;
}

/**
 * Generates a fully self-contained docker-compose.yml with all values resolved inline.
 * No ${VAR} interpolation -- everything is baked in.
 */
export function generateComposeExport(
  state: WizardState,
  registry: ServiceRegistry,
  storagePath: string = "/var/lib/jarvis",
): string {
  const allEnabled = getAllEnabledServices(state, registry);
  const enabledIds = allEnabled.map((s) => s.id);
  const infra = getInfraForServices(enabledIds, registry);

  // Add mosquitto if available
  const mosquitto = registry.infrastructure.find((i) => i.id === "mosquitto");
  if (mosquitto && !infra.some((i) => i.id === "mosquitto")) {
    infra.push(mosquitto);
  }

  // Generate app keys for each service (except jarvis-admin)
  const appKeys = new Map<string, AppKeyEntry>();
  for (const svc of allEnabled) {
    if (svc.id === "jarvis-admin") continue;
    appKeys.set(svc.id, generateAppKey(svc.id));
  }

  const secrets: SecretsMap = {
    pgPassword: state.secrets["POSTGRES_PASSWORD"] ?? "changeme",
    redisPassword: state.secrets["REDIS_PASSWORD"] ?? "changeme",
    authSecretKey: state.secrets["AUTH_SECRET_KEY"] ?? "changeme",
    configAdminToken: state.secrets["JARVIS_CONFIG_ADMIN_TOKEN"] ?? "changeme",
    authAdminToken: state.secrets["JARVIS_AUTH_ADMIN_TOKEN"] ?? "changeme",
    adminApiKey: state.secrets["ADMIN_API_KEY"] ?? "changeme",
    dbUser: state.dbUser || "jarvis",
  };

  // Collect databases from enabled services
  const databases = allEnabled
    .filter((s) => s.database)
    .map((s) => s.database!);
  const primaryDb = "jarvis_config";

  const lines: string[] = [];

  lines.push("# Jarvis Voice Assistant - Self-Contained Docker Compose");
  lines.push("# Generated by Jarvis Installer (compose-export mode)");
  lines.push("# All values are resolved inline - no .env file required");
  lines.push("");
  lines.push("services:");

  // --- Infrastructure ---
  lines.push("");
  lines.push("  # ============================================================");
  lines.push("  # Infrastructure");
  lines.push("  # ============================================================");

  // PostgreSQL
  if (infra.some((i) => i.id === "postgres")) {
    const pgHostPort = state.infraPortOverrides["postgres"] ?? 5432;
    const additionalDbs = databases.filter((db) => db !== primaryDb);

    lines.push("");
    lines.push("  postgres:");
    lines.push("    image: postgres:16-alpine");
    lines.push("    container_name: jarvis-postgres");
    lines.push("    ports:");
    lines.push(`      - "${pgHostPort}:5432"`);
    lines.push("    environment:");
    lines.push(`      POSTGRES_USER: "${secrets.dbUser}"`);
    lines.push(`      POSTGRES_PASSWORD: "${secrets.pgPassword}"`);
    lines.push(`      POSTGRES_DB: "${primaryDb}"`);
    if (additionalDbs.length > 0) {
      const createLines = additionalDbs.map(
        (db) => `SELECT 'CREATE DATABASE ${db}' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${db}')\\\\gexec`,
      );
      lines.push("    command:");
      lines.push("      - bash");
      lines.push("      - -c");
      lines.push("      - |");
      lines.push(`        cat > /docker-entrypoint-initdb.d/init.sql << 'EOSQL'`);
      for (const stmt of createLines) {
        lines.push(`        ${stmt}`);
      }
      lines.push("        EOSQL");
      lines.push("        exec docker-entrypoint.sh postgres");
    }
    lines.push("    healthcheck:");
    lines.push(`      test: ["CMD-SHELL", "pg_isready -U ${secrets.dbUser}"]`);
    lines.push("      interval: 10s");
    lines.push("      timeout: 5s");
    lines.push("      retries: 5");
    lines.push("    volumes:");
    lines.push(`      - ${storagePath}/postgres:/var/lib/postgresql/data`);
    lines.push("    networks:");
    lines.push("      - jarvis");
    lines.push("    restart: unless-stopped");
  }

  // Redis
  if (infra.some((i) => i.id === "redis")) {
    const redisHostPort = state.infraPortOverrides["redis"] ?? 6379;
    lines.push("");
    lines.push("  redis:");
    lines.push("    image: redis:7-alpine");
    lines.push("    container_name: jarvis-redis");
    lines.push("    ports:");
    lines.push(`      - "${redisHostPort}:6379"`);
    lines.push(`    command: redis-server --requirepass "${secrets.redisPassword}"`);
    lines.push("    volumes:");
    lines.push(`      - ${storagePath}/redis:/data`);
    lines.push("    networks:");
    lines.push("      - jarvis");
    lines.push("    restart: unless-stopped");
  }

  // Loki
  if (infra.some((i) => i.id === "loki")) {
    const lokiHostPort = state.infraPortOverrides["loki"] ?? 3100;
    lines.push("");
    lines.push("  loki:");
    lines.push("    image: grafana/loki:2.9.0");
    lines.push("    container_name: jarvis-loki");
    lines.push("    ports:");
    lines.push(`      - "${lokiHostPort}:3100"`);
    lines.push("    volumes:");
    lines.push(`      - ${storagePath}/loki:/loki`);
    lines.push("    networks:");
    lines.push("      - jarvis");
    lines.push("    restart: unless-stopped");
  }

  // Grafana
  if (infra.some((i) => i.id === "grafana")) {
    const grafanaHostPort = state.infraPortOverrides["grafana"] ?? 3001;
    lines.push("");
    lines.push("  grafana:");
    lines.push("    image: grafana/grafana:latest");
    lines.push("    container_name: jarvis-grafana");
    lines.push("    ports:");
    lines.push(`      - "${grafanaHostPort}:3000"`);
    lines.push("    environment:");
    lines.push('      GF_SECURITY_ADMIN_PASSWORD: "jarvis"');
    lines.push("    volumes:");
    lines.push(`      - ${storagePath}/grafana:/var/lib/grafana`);
    lines.push("    networks:");
    lines.push("      - jarvis");
    lines.push("    restart: unless-stopped");
  }

  // Mosquitto
  if (infra.some((i) => i.id === "mosquitto")) {
    const mqttHostPort = state.infraPortOverrides["mosquitto"] ?? 1884;
    lines.push("");
    lines.push("  mosquitto:");
    lines.push("    image: eclipse-mosquitto:2");
    lines.push("    container_name: jarvis-mosquitto");
    lines.push("    ports:");
    lines.push(`      - "${mqttHostPort}:1883"`);
    lines.push("    command: mosquitto -c /dev/null -p 1883 -v");
    lines.push("    volumes:");
    lines.push(`      - ${storagePath}/mosquitto:/mosquitto/data`);
    lines.push("    networks:");
    lines.push("      - jarvis");
    lines.push("    restart: unless-stopped");
  }

  // --- Services ---
  lines.push("");
  lines.push("  # ============================================================");
  lines.push("  # Jarvis Services");
  lines.push("  # ============================================================");

  for (const service of allEnabled) {
    lines.push("");
    lines.push(
      ...generateExportServiceBlock(
        service,
        state,
        registry,
        appKeys,
        secrets,
        allEnabled,
      ),
    );
  }

  // Networks
  lines.push("");
  lines.push("networks:");
  lines.push("  jarvis:");
  lines.push("    driver: bridge");

  lines.push("");
  return lines.join("\n");
}

function getContainerPort(service: ServiceDefinition): number {
  return service.containerPort ?? service.port;
}

function generateExportServiceBlock(
  service: ServiceDefinition,
  state: WizardState,
  registry: ServiceRegistry,
  appKeys: Map<string, AppKeyEntry>,
  secrets: SecretsMap,
  allEnabled: ServiceDefinition[],
): string[] {
  const lines: string[] = [];
  const hostPort = state.portOverrides[service.id] ?? service.port;
  const containerPort = getContainerPort(service);

  lines.push(`  ${service.id}:`);
  lines.push(`    image: ${service.image}`);
  lines.push(`    container_name: ${service.id}`);

  // Ports
  lines.push("    ports:");
  lines.push(`      - "${hostPort}:${containerPort}"`);

  // Environment
  lines.push("    environment:");

  // DATABASE_URL
  if (service.database) {
    const driver = service.dbDriverPrefix ?? "postgresql://";
    const dbUrl = `${driver}${secrets.dbUser}:${secrets.pgPassword}@postgres:5432/${service.database}`;
    lines.push(`      DATABASE_URL: "${dbUrl}"`);
    lines.push(`      MIGRATIONS_DATABASE_URL: "${dbUrl}"`);
  }

  // App-to-app credentials
  const appKey = appKeys.get(service.id);
  if (appKey) {
    lines.push(`      JARVIS_APP_ID: "${service.id}"`);
    lines.push(`      JARVIS_APP_KEY: "${appKey.rawKey}"`);
  }

  // Service-specific env vars (skip DATABASE_URL and MIGRATIONS_DATABASE_URL, already handled)
  for (const env of service.envVars) {
    if (env.name === "DATABASE_URL" || env.name === "MIGRATIONS_DATABASE_URL") continue;

    if (env.secretRef) {
      const value = state.secrets[env.secretRef] ?? "";
      lines.push(`      ${env.name}: "${value}"`);
    } else if (env.default) {
      lines.push(`      ${env.name}: "${env.default}"`);
    }
  }

  // Service-specific extra env vars
  if (service.id === "jarvis-auth") {
    lines.push(`      JARVIS_AUTH_BASE_URL: "http://jarvis-auth:${containerPort}"`);
  }

  if (service.id === "jarvis-command-center" && state.llmInterface) {
    lines.push(`      LLM_INTERFACE_SEED: "${state.llmInterface}"`);
  }

  if (service.id === "jarvis-settings-server") {
    lines.push(`      JARVIS_AUTH_SECRET_KEY: "${secrets.authSecretKey}"`);
    lines.push('      JARVIS_AUTH_ALGORITHM: "HS256"');
  }

  if (service.id === "jarvis-admin") {
    lines.push('      JARVIS_DEPLOY_MODE: "compose-export"');
  }

  // Whisper model override
  const isWhisper = service.id === "jarvis-whisper-api";
  const nonDefaultWhisper = isWhisper && state.whisperModel !== "base.en";
  if (nonDefaultWhisper) {
    lines.push(`      WHISPER_MODEL: "/models/ggml-${state.whisperModel}.bin"`);
  }

  // Command with seed scripts
  if (service.id === "jarvis-auth") {
    lines.push("    command:");
    lines.push("      - sh");
    lines.push("      - -c");
    lines.push("      - |");
    for (const line of generateAuthSeedScript(appKeys, containerPort).split("\n")) {
      lines.push(`        ${line}`);
    }
  } else if (service.id === "jarvis-config-service") {
    lines.push("    command:");
    lines.push("      - sh");
    lines.push("      - -c");
    lines.push("      - |");
    for (const line of generateConfigSeedScript(allEnabled, containerPort).split("\n")) {
      lines.push(`        ${line}`);
    }
  } else if (service.id === "jarvis-command-center") {
    lines.push("    command:");
    lines.push("      - sh");
    lines.push("      - -c");
    lines.push("      - |");
    lines.push("        python -m alembic upgrade head");
    lines.push(`        exec uvicorn app.main:app --host 0.0.0.0 --port ${containerPort}`);
  }

  // Dependencies
  if (service.dependsOn.length > 0) {
    lines.push("    depends_on:");
    for (const dep of service.dependsOn) {
      const isInfra = registry.infrastructure.some((i) => i.id === dep);
      if (isInfra && dep === "postgres") {
        lines.push(`      ${dep}:`);
        lines.push("        condition: service_healthy");
      } else if (isInfra) {
        lines.push(`      ${dep}:`);
        lines.push("        condition: service_started");
      } else {
        const depEnabled = allEnabled.some((s) => s.id === dep);
        if (depEnabled) {
          lines.push(`      ${dep}:`);
          lines.push("        condition: service_started");
        }
      }
    }
  }

  // Volumes (whisper non-default model)
  if (nonDefaultWhisper) {
    lines.push("    volumes:");
    lines.push("      - ./models:/models:ro");
  }

  // GPU config
  if (service.gpu) {
    lines.push("    deploy:");
    lines.push("      resources:");
    lines.push("        reservations:");
    lines.push("          devices:");
    lines.push("            - driver: nvidia");
    lines.push("              count: all");
    lines.push("              capabilities: [gpu]");
  }

  // Healthcheck
  lines.push("    healthcheck:");
  lines.push(
    `      test: ["CMD", "curl", "-f", "http://localhost:${containerPort}${service.healthCheck}"]`,
  );
  lines.push("      interval: 30s");
  lines.push("      timeout: 10s");
  lines.push("      retries: 3");

  lines.push("    networks:");
  lines.push("      - jarvis");
  lines.push("    restart: unless-stopped");

  return lines;
}

function generateAuthSeedScript(
  appKeys: Map<string, AppKeyEntry>,
  authContainerPort: number,
): string {
  const clientLines: string[] = [];
  for (const [, entry] of appKeys) {
    // Escape single quotes in bcrypt hash for Python string
    const escapedBcrypt = entry.bcryptHash.replace(/'/g, "\\'");
    clientLines.push(
      `    ('${entry.appId}', '${escapedBcrypt}'),`,
    );
  }

  return `python -m alembic upgrade head
python -c "
from app.db.session import SessionLocal
from app.models.app_client import AppClient
db = SessionLocal()
clients = [
${clientLines.join("\n")}
]
for app_id, hashed_key in clients:
    exists = db.query(AppClient).filter(AppClient.app_id == app_id).first()
    if not exists:
        db.add(AppClient(app_id=app_id, hashed_key=hashed_key, description='Auto-seeded by installer'))
        print(f'Seeded app client: {app_id}')
db.commit()
db.close()
print('Auth seed complete')
"
exec uvicorn app.main:app --host 0.0.0.0 --port ${authContainerPort}`;
}

function generateConfigSeedScript(
  allEnabled: ServiceDefinition[],
  configContainerPort: number,
): string {
  const serviceLines: string[] = [];
  for (const svc of allEnabled) {
    const cPort = getContainerPort(svc);
    serviceLines.push(
      `    ('${svc.id}', '${svc.name}', 'http://${svc.id}:${cPort}'),`,
    );
  }

  return `python -m alembic upgrade head
python -c "
from app.db.session import SessionLocal
from app.models.service import Service
db = SessionLocal()
services = [
${serviceLines.join("\n")}
]
for service_id, name, url in services:
    exists = db.query(Service).filter(Service.service_id == service_id).first()
    if not exists:
        db.add(Service(service_id=service_id, name=name, url=url))
        print(f'Registered service: {service_id} -> {url}')
db.commit()
db.close()
print('Config seed complete')
"
exec uvicorn app.main:app --host 0.0.0.0 --port ${configContainerPort}`;
}
