import type { WizardState } from "@/types/wizard";
import type { ServiceRegistry } from "@/types/service-registry";
import { getCoreServices, getRecommendedServices, getOptionalServices, getRequiredInfrastructure } from "@/lib/service-registry";
import { serviceIdToPortVar } from "@/lib/port-utils";
import { SECRET_KEYS } from "@/lib/secret-generator";

export function generateEnv(state: WizardState, registry: ServiceRegistry): string {
  const lines: string[] = [];

  lines.push("# Jarvis Configuration");
  lines.push("# Generated by Jarvis Installer");
  lines.push("");

  // Secrets
  lines.push("# --- Secrets ---");
  for (const key of SECRET_KEYS) {
    const value = state.secrets[key] ?? "";
    lines.push(`${key}=${value}`);
  }
  lines.push("");

  // Database
  lines.push("# --- Database ---");
  lines.push(`DB_USER=${state.dbUser}`);
  lines.push("");

  // Service ports
  const coreServices = getCoreServices(registry);
  const enabledRecommended = getRecommendedServices(registry).filter((s) =>
    state.enabledModules.includes(s.id),
  );
  const enabledOptional = getOptionalServices(registry).filter((s) =>
    state.enabledModules.includes(s.id),
  );
  const allEnabled = [...coreServices, ...enabledRecommended, ...enabledOptional];

  lines.push("# --- Service Ports ---");
  for (const svc of allEnabled) {
    const portVar = serviceIdToPortVar(svc.id);
    const port = state.portOverrides[svc.id] ?? svc.port;
    lines.push(`${portVar}=${port}`);
  }
  lines.push("");

  // Infrastructure ports
  const enabledIds = allEnabled.map((s) => s.id);
  const infra = getRequiredInfrastructure(registry, enabledIds);

  // Always include redis
  const redis = registry.infrastructure.find((i) => i.id === "redis");
  if (redis && !infra.some((i) => i.id === "redis")) {
    infra.push(redis);
  }

  // Include grafana if loki is present
  const hasLoki = infra.some((i) => i.id === "loki");
  const grafana = registry.infrastructure.find((i) => i.id === "grafana");
  if (hasLoki && grafana && !infra.some((i) => i.id === "grafana")) {
    infra.push(grafana);
  }

  lines.push("# --- Infrastructure Ports ---");
  for (const inf of infra) {
    const portVar = serviceIdToPortVar(inf.id);
    const port = state.infraPortOverrides[inf.id] ?? inf.port;
    lines.push(`${portVar}=${port}`);
  }
  lines.push("");

  // Jarvis Relay
  if (state.relayEnabled) {
    lines.push("# --- Jarvis Relay ---");
    lines.push(`JARVIS_RELAY_URL=${state.relayUrl || "https://relay.jarvisautomation.io"}`);
    lines.push("");
  }

  // Release Track
  lines.push("# --- Release Track ---");
  lines.push(`JARVIS_IMAGE_TAG=${state.releaseTrack === "dev" ? "dev" : "latest"}`);
  lines.push("");

  return lines.join("\n");
}
