import type { WizardState } from "@/types/wizard";
import type { ServiceRegistry } from "@/types/service-registry";
import { getCoreServices, getRecommendedServices, getOptionalServices, getRequiredInfrastructure } from "@/lib/service-registry";
import { serviceIdToPortVar } from "@/lib/port-utils";
import { SECRET_KEYS, generateHexSecret } from "@/lib/secret-generator";

export function generateEnv(state: WizardState, registry: ServiceRegistry): string {
  const lines: string[] = [];

  lines.push("# Jarvis Configuration");
  lines.push("# Generated by Jarvis Installer");
  lines.push("");

  // Secrets. NEVER emit an empty value (mirrors jarvis-admin): a blank
  // secret line ships a service with auth silently disabled — the exact
  // blank-GRAFANA_ADMIN_PASSWORD bug the compose↔env contract test caught
  // on 2026-07-07. A wizard-provided value wins; a genuinely missing one
  // gets a fresh strong secret (passwords 16 bytes, tokens/keys 32).
  lines.push("# --- Secrets ---");
  for (const key of SECRET_KEYS) {
    const value = state.secrets[key] || generateHexSecret(key.includes("PASSWORD") ? 16 : 32);
    lines.push(`${key}=${value}`);
  }
  lines.push("");

  // Database
  lines.push("# --- Database ---");
  lines.push(`DB_USER=${state.dbUser}`);
  lines.push("");

  // Service ports
  const coreServices = getCoreServices(registry);
  const enabledRecommended = getRecommendedServices(registry).filter((s) =>
    state.enabledModules.includes(s.id),
  );
  const enabledOptional = getOptionalServices(registry).filter((s) =>
    state.enabledModules.includes(s.id),
  );
  const allEnabled = [...coreServices, ...enabledRecommended, ...enabledOptional];

  lines.push("# --- Service Ports ---");
  for (const svc of allEnabled) {
    const portVar = serviceIdToPortVar(svc.id);
    const port = state.portOverrides[svc.id] ?? svc.port;
    lines.push(`${portVar}=${port}`);
  }
  lines.push("");

  // Infrastructure ports
  const enabledIds = allEnabled.map((s) => s.id);
  const infra = getRequiredInfrastructure(registry, enabledIds);

  // Always include redis
  const redis = registry.infrastructure.find((i) => i.id === "redis");
  if (redis && !infra.some((i) => i.id === "redis")) {
    infra.push(redis);
  }

  // Include grafana if loki is present
  const hasLoki = infra.some((i) => i.id === "loki");
  const grafana = registry.infrastructure.find((i) => i.id === "grafana");
  if (hasLoki && grafana && !infra.some((i) => i.id === "grafana")) {
    infra.push(grafana);
  }

  lines.push("# --- Infrastructure Ports ---");
  for (const inf of infra) {
    const portVar = serviceIdToPortVar(inf.id);
    const port = state.infraPortOverrides[inf.id] ?? inf.port;
    lines.push(`${portVar}=${port}`);
  }
  lines.push("");

  // Jarvis Relay
  if (state.relayEnabled) {
    lines.push("# --- Jarvis Relay ---");
    lines.push(`JARVIS_RELAY_URL=${state.relayUrl || "https://relay.jarvisautomation.io"}`);
    // Household JWT consumed by jarvis-notifications for push delivery.
    // Empty placeholder on fresh install — user pastes their household JWT.
    lines.push(`JARVIS_RELAY_HOUSEHOLD_JWT=${state.relayHouseholdJwt ?? ""}`);
    lines.push("");
  }

  // Release Track
  lines.push("# --- Release Track ---");
  lines.push(`JARVIS_IMAGE_TAG=${state.releaseTrack === "dev" ? "dev" : "latest"}`);
  lines.push("");

  // GPU backends — the ONLY durable record of these choices (the compose
  // pins images by digest). jarvis-admin's reconcile reconstructs its state
  // from .env; without these keys a later reconcile silently downgrades
  // whisper to the CPU image and strips TTS's GPU passthrough.
  // Image pinning policy — read back by jarvis-admin's reconcile.
  lines.push("# --- Image Pinning (opt-in supply-chain hardening) ---");
  lines.push(`PIN_IMAGES=${state.pinImages ? "true" : "false"}`);
  lines.push("");

  lines.push("# --- GPU Backends ---");
  lines.push(`WHISPER_BACKEND=${state.whisperBackend}`);
  lines.push(`TTS_BACKEND=${state.ttsBackend}`);
  if (state.ttsBackend === "cuda") {
    lines.push("TTS_GPU_DEVICE=0");
  }
  lines.push("");

  return lines.join("\n");
}
