import type { WizardState } from "@/types/wizard";
import type { ServiceRegistry } from "@/types/service-registry";

export function generateEnv(state: WizardState, _registry: ServiceRegistry): string {
  const lines: string[] = [];

  lines.push("# Jarvis Environment Configuration");
  lines.push("# Generated by Jarvis Installer");
  lines.push("");

  // Inference
  lines.push("# Inference Configuration");
  lines.push(`INFERENCE_MODE=${state.inferenceMode}`);
  if (state.recommendation) {
    lines.push(`MODEL_ID=${state.recommendation.modelId}`);
    lines.push(`QUANTIZATION=${state.recommendation.quantization}`);
    lines.push(`GPU_LAYERS=${state.recommendation.gpuLayers}`);
  }
  lines.push("");

  // Database
  lines.push("# Database");
  lines.push("DATABASE_URL=postgresql://jarvis:jarvis@postgres:5432/jarvis");
  lines.push("POSTGRES_USER=jarvis");
  lines.push("POSTGRES_PASSWORD=CHANGE_ME");
  lines.push("POSTGRES_DB=jarvis");
  lines.push("");

  // Auth
  lines.push("# Auth");
  lines.push("SECRET_KEY=CHANGE_ME");
  lines.push("ADMIN_API_KEY=CHANGE_ME");
  lines.push("");

  // Services
  lines.push("# Service URLs");
  lines.push("JARVIS_AUTH_BASE_URL=http://jarvis-auth:8007");
  lines.push("LOKI_URL=http://loki:3100");
  lines.push("");

  // Wake word
  lines.push("# Wake Word");
  lines.push(`WAKE_WORD=${state.wakeWord}`);
  lines.push("");

  // Home Assistant
  if (state.homeAssistant.enabled) {
    lines.push("# Home Assistant");
    lines.push(`HA_URL=${state.homeAssistant.url}`);
    lines.push(`HA_TOKEN=${state.homeAssistant.token}`);
    lines.push("");
  }

  // Grafana
  lines.push("# Grafana");
  lines.push("GF_SECURITY_ADMIN_PASSWORD=jarvis");

  return lines.join("\n");
}
