#!/usr/bin/env bash
set -euo pipefail

# Jarvis Installer
# Usage: curl -fsSL <url>/install.sh | bash -s -- [flags]

JARVIS_DIR="${HOME}/jarvis"
REPO_BASE_URL="https://raw.githubusercontent.com/alexanderberardi/jarvis-installer/main"

# Defaults
PROFILE="gpu"
MODEL=""
QUANTIZATION=""
GPU_LAYERS=""
MODULES=""
WAKE_WORD="jarvis"
HA_URL=""
HA_TOKEN=""

# ─── Parse Arguments ────────────────────────────────────────────────────────

while [[ $# -gt 0 ]]; do
  case $1 in
    --profile)
      PROFILE="$2"
      shift 2
      ;;
    --model)
      MODEL="$2"
      shift 2
      ;;
    --quantization)
      QUANTIZATION="$2"
      shift 2
      ;;
    --gpu-layers)
      GPU_LAYERS="$2"
      shift 2
      ;;
    --modules)
      MODULES="$2"
      shift 2
      ;;
    --wake-word)
      WAKE_WORD="$2"
      shift 2
      ;;
    --ha-url)
      HA_URL="$2"
      shift 2
      ;;
    --ha-token)
      HA_TOKEN="$2"
      shift 2
      ;;
    --help)
      echo "Usage: install.sh [options]"
      echo ""
      echo "Options:"
      echo "  --profile <gpu|cpu>       Inference profile (default: gpu)"
      echo "  --model <model-id>        Model identifier"
      echo "  --quantization <quant>    Quantization level (e.g., q4_k_m, q8_0)"
      echo "  --gpu-layers <n|all>      Number of GPU layers (or 'all')"
      echo "  --modules <list>          Comma-separated optional modules"
      echo "  --wake-word <word>        Wake word (default: jarvis)"
      echo "  --ha-url <url>            Home Assistant URL"
      echo "  --ha-token <token>        Home Assistant access token"
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      exit 1
      ;;
  esac
done

# ─── Color Helpers ──────────────────────────────────────────────────────────

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

info()  { echo -e "${BLUE}[INFO]${NC} $*"; }
ok()    { echo -e "${GREEN}[OK]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
err()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }

# ─── Prerequisite Checks ───────────────────────────────────────────────────

info "Checking prerequisites..."

if ! command -v docker &>/dev/null; then
  err "Docker is not installed. Please install Docker first:"
  err "  https://docs.docker.com/get-docker/"
  exit 1
fi
ok "Docker found: $(docker --version)"

if ! docker compose version &>/dev/null; then
  err "Docker Compose v2 is not installed."
  err "  Install it via: https://docs.docker.com/compose/install/"
  exit 1
fi
ok "Docker Compose found: $(docker compose version --short)"

if [[ "$PROFILE" == "gpu" ]]; then
  if command -v nvidia-smi &>/dev/null; then
    ok "NVIDIA GPU detected: $(nvidia-smi --query-gpu=name --format=csv,noheader,nounits | head -1)"
    if ! docker info 2>/dev/null | grep -q "nvidia"; then
      warn "nvidia-container-toolkit may not be installed."
      warn "  GPU passthrough might not work. Install from:"
      warn "  https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html"
    fi
  else
    warn "GPU profile selected but nvidia-smi not found."
    warn "  If using AMD or Apple Silicon, GPU support may work via other drivers."
  fi
fi

# ─── Create Install Directory ──────────────────────────────────────────────

info "Creating ${JARVIS_DIR}..."
mkdir -p "${JARVIS_DIR}"
cd "${JARVIS_DIR}"

# ─── Download Configuration Files ──────────────────────────────────────────

info "Downloading configuration files..."

curl -fsSL "${REPO_BASE_URL}/public/service-registry.json" -o service-registry.json
ok "Downloaded service-registry.json"

# ─── Generate .env ─────────────────────────────────────────────────────────

info "Generating .env file..."

# Generate random secrets
generate_secret() {
  openssl rand -hex 32 2>/dev/null || head -c 64 /dev/urandom | base64 | tr -d '=/+' | head -c 64
}

SECRET_KEY=$(generate_secret)
ADMIN_API_KEY=$(generate_secret)
POSTGRES_PASSWORD=$(generate_secret)

cat > .env << ENVEOF
# Jarvis Environment Configuration
# Generated by Jarvis Installer on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Inference Configuration
INFERENCE_MODE=${PROFILE}
MODEL_ID=${MODEL}
QUANTIZATION=${QUANTIZATION}
GPU_LAYERS=${GPU_LAYERS}

# Database
DATABASE_URL=postgresql://jarvis:${POSTGRES_PASSWORD}@postgres:5432/jarvis
POSTGRES_USER=jarvis
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=jarvis

# Auth
SECRET_KEY=${SECRET_KEY}
ADMIN_API_KEY=${ADMIN_API_KEY}

# Service URLs
JARVIS_AUTH_BASE_URL=http://jarvis-auth:8007
LOKI_URL=http://loki:3100

# Wake Word
WAKE_WORD=${WAKE_WORD}

# Grafana
GF_SECURITY_ADMIN_PASSWORD=$(generate_secret | head -c 16)
ENVEOF

# Add HA config if provided
if [[ -n "$HA_URL" ]]; then
  cat >> .env << HAEOF

# Home Assistant
HA_URL=${HA_URL}
HA_TOKEN=${HA_TOKEN}
HAEOF
fi

ok "Generated .env with secure random secrets"

# ─── Generate docker-compose.yml ───────────────────────────────────────────

info "Generating docker-compose.yml..."

# Build compose profiles for docker compose command
COMPOSE_PROFILES=""
if [[ -n "$MODULES" ]]; then
  # Convert comma-separated to space-separated for compose profiles
  IFS=',' read -ra MODULE_ARRAY <<< "$MODULES"
  for module in "${MODULE_ARRAY[@]}"; do
    COMPOSE_PROFILES="${COMPOSE_PROFILES} --profile ${module}"
  done
fi

# Download the pre-built docker-compose.yml from the repo
# In production, this would be generated from the registry
curl -fsSL "${REPO_BASE_URL}/docker-compose.yml" -o docker-compose.yml 2>/dev/null || {
  info "No pre-built docker-compose.yml found, generating..."
  # Minimal compose file as fallback
  cat > docker-compose.yml << 'COMPOSEEOF'
version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: jarvis-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-jarvis}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB:-jarvis}
    volumes:
      - jarvis-postgres-data:/var/lib/postgresql/data
    networks:
      - jarvis
    restart: unless-stopped

  loki:
    image: grafana/loki:2.9.0
    container_name: jarvis-loki
    ports:
      - "3100:3100"
    volumes:
      - jarvis-loki-data:/loki
    networks:
      - jarvis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: jarvis-redis
    ports:
      - "6379:6379"
    volumes:
      - jarvis-redis-data:/data
    networks:
      - jarvis
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: jarvis-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-jarvis}
    volumes:
      - jarvis-grafana-data:/var/lib/grafana
    networks:
      - jarvis
    restart: unless-stopped

  jarvis-auth:
    image: ghcr.io/jarvis/jarvis-auth:latest
    container_name: jarvis-auth
    ports:
      - "8007:8007"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      postgres:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8007/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - jarvis
    restart: unless-stopped

  jarvis-logs:
    image: ghcr.io/jarvis/jarvis-logs:latest
    container_name: jarvis-logs
    ports:
      - "8006:8006"
    environment:
      - LOKI_URL=${LOKI_URL:-http://loki:3100}
    depends_on:
      loki:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8006/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - jarvis
    restart: unless-stopped

  jarvis-config-service:
    image: ghcr.io/jarvis/jarvis-config-service:latest
    container_name: jarvis-config-service
    ports:
      - "8013:8013"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      postgres:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8013/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - jarvis
    restart: unless-stopped

  jarvis-whisper:
    image: ghcr.io/jarvis/jarvis-whisper-api:latest
    container_name: jarvis-whisper
    ports:
      - "8012:8012"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8012/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - jarvis
    restart: unless-stopped

  jarvis-tts:
    image: ghcr.io/jarvis/jarvis-tts:latest
    container_name: jarvis-tts
    ports:
      - "8009:8009"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8009/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - jarvis
    restart: unless-stopped

  jarvis-command-center:
    image: ghcr.io/jarvis/jarvis-command-center:latest
    container_name: jarvis-command-center
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ADMIN_API_KEY=${ADMIN_API_KEY}
      - JARVIS_AUTH_BASE_URL=${JARVIS_AUTH_BASE_URL:-http://jarvis-auth:8007}
    depends_on:
      postgres:
        condition: service_started
      jarvis-auth:
        condition: service_healthy
      jarvis-whisper:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - jarvis
    restart: unless-stopped

  jarvis-mcp:
    image: ghcr.io/jarvis/jarvis-mcp:latest
    container_name: jarvis-mcp
    ports:
      - "8011:8011"
    depends_on:
      jarvis-logs:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8011/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - jarvis
    restart: unless-stopped

  jarvis-admin:
    image: ghcr.io/jarvis/jarvis-admin:latest
    container_name: jarvis-admin
    ports:
      - "3000:3000"
    depends_on:
      jarvis-auth:
        condition: service_healthy
      jarvis-command-center:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - jarvis
    restart: unless-stopped

  jarvis-ocr-service:
    image: ghcr.io/jarvis/jarvis-ocr-service:latest
    container_name: jarvis-ocr-service
    profiles: ["jarvis-ocr-service"]
    ports:
      - "5009:5009"
    environment:
      - JARVIS_AUTH_BASE_URL=${JARVIS_AUTH_BASE_URL:-http://jarvis-auth:8007}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5009/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - jarvis
    restart: unless-stopped

  jarvis-recipes:
    image: ghcr.io/jarvis/jarvis-recipes-server:latest
    container_name: jarvis-recipes
    profiles: ["jarvis-recipes"]
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      postgres:
        condition: service_started
      jarvis-ocr-service:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - jarvis
    restart: unless-stopped

networks:
  jarvis:
    driver: bridge

volumes:
  jarvis-postgres-data:
  jarvis-loki-data:
  jarvis-redis-data:
  jarvis-grafana-data:
COMPOSEEOF
}

ok "Generated docker-compose.yml"

# ─── Start Services ────────────────────────────────────────────────────────

info "Starting Jarvis stack..."

# shellcheck disable=SC2086
docker compose ${COMPOSE_PROFILES} up -d

echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║         Jarvis installed successfully!       ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${BLUE}Install directory:${NC} ${JARVIS_DIR}"
echo -e "  ${BLUE}Admin dashboard:${NC}  http://localhost:3000"
echo -e "  ${BLUE}Grafana:${NC}          http://localhost:3001"
echo ""
echo -e "  ${YELLOW}Useful commands:${NC}"
echo "    cd ${JARVIS_DIR}"
echo "    docker compose ps          # Check service status"
echo "    docker compose logs -f     # Follow logs"
echo "    docker compose down        # Stop all services"
echo ""
echo -e "  ${YELLOW}Health checks:${NC}"
echo "    curl http://localhost:8007/health   # Auth"
echo "    curl http://localhost:8002/health   # Command Center"
echo "    curl http://localhost:8006/health   # Logs"
echo ""
